import type { Metadata } from "next";
import { Inter, Recursive } from "next/font/google";
import "./globals.css";
import { Navbar } from "./_components/navbar";
import { Footer } from "./_components/footer";
import { Toaster } from "@/components/ui/toaster";
import { Providers } from "@/providers/Providers";

const inter = Recursive({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <Navbar />
            <main className="flex flex-col min-h-[calc(100vh-3.5rem-1px)] bg-gray-50">
               <div className="flex-1 flex flex-col h-full">
                  <Providers>{children}</Providers>
               </div>
               <Footer />
            </main>
            <Toaster />
         </body>
      </html>
   );
}
